version: '3.7'

services:
  ffprobe-wasm:
    build: .
    volumes:
      - "./ffmpeg:/compile/ffmpeg"
      - "./dist:/dist"
      - "./.cache/modules:/emsdk/upstream/emscripten/cache"
      - "./.cache/data:/emsdk_portable/.data/cache/wasm"
      - "./src:/src"